apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  jgroups-cluster-password:
    {{ .Values.jgroupsClusterPassword | b64enc }}
{{- if .Values.enableTls }}
  jgroups-encrypt-password:
    {{ .Values.jgroupsEncryptPassword | b64enc }}
{{- end }}
